[package]
name = "publio"
version = "0.1.0"
authors = ["huangjiahua <hah@whu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
log = "0.4.0"
env_logger = "0.6.2"
